---

name: lintTester


on:
  push:
    branches: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]


jobs:
  build:
    # Name the Job
    name: lintCodeTest
    # Set the agent to run on
    runs-on: ubuntu-latest


    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: lintTester
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_STANDARD: false
